%YAML:1.0

#common parameters
imu_topic: "/imu/data"
image_topic: "/hikrobot_infrared_camera/rgb"
output_path: "/home/shaozu/output/"

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 512
distortion_parameters:
   k1: -0.15108865423029505
   k2: 0.027321998823287064
   p1: 0.003548910446050655
   p2: -0.0044816225733077
projection_parameters:
   fx: 386.32894301034275
   fy: 387.8691278754553
   cx: 322.03021157684685
   cy: 255.37626933631785

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.99998703,-0.00473710,-0.00186957,
          0.00189043,0.00440238,0.99998852,
          -0.00472881,-0.99997909,0.00441128]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.33255033,0.25015487,-0.01718281]

#feature traker paprameters
max_cnt: 200            # max feature number in feature tracking
min_dist: 20            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 0             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
# acc_n: 0.1 #0.2 #0.08          # accelerometer measurement noise standard deviation. #0.2   0.04
# gyr_n: 0.01 #0.005 #0.004         # gyroscope measurement noise standard deviation.     #0.05  0.004
# acc_w: 0.001 #0.002 #0.00004         # accelerometer bias random work noise standard deviation.  #0.02
# gyr_w: 0.0001 #4.0e-5 #2.0e-6       # gyroscope bias random work noise standard deviation.     #4.0e-5
acc_n: 0.2 #0.08          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.005 #0.004         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.002 #0.00004         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 4.0e-5 #2.0e-6       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#loop closure parameters
loop_closure: 1                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/shaozu/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: -0.082154                            # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
